pipeline:
  delegateSelectors:
  - demo
  identifier: demo
  name: demo
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
  - stage:
      description: ''
      identifier: teststage
      name: test-stage
      spec:
        execution:
          steps:
          - step:
              identifier: ShellScript1
              name: Shell-Script-1
              spec:
                environmentVariables: []
                onDelegate: true
                outputVariables: []
                shell: Bash
                source:
                  spec:
                    script: echo "Dummy Pipeline"
                  type: Inline
              timeout: 10m
              type: ShellScript
      tags: {}
      type: Custom
  tags: {}
